<?php

namespace Database\Seeders;

use App\Models\KelompokPertanyaan;
use App\Models\RefSubpertanyaan2021;
use Illuminate\Database\Seeder;

/**
 * Seeder RefSubpertanyaan2021Seeder
 *
 * Fungsi: Mengisi seluruh butir pertanyaan instrumen Tracer Study 2021 (Universitas).
 * Status 'wajib' (1 = Wajib Diisi, 0 = Opsional):
 * - Wajib (1): F1 (NIM), F2A (Nama), F2B (Telepon), F2C (Email), F2D (Alamat),
 *   BIO_TEMPAT_LAHIR, BIO_TANGGAL_LAHIR, BIO_JK, BIO_TGL_LULUS, BIO_JUDUL_TA, BIO_NIK, BIO_NPWP,
 *   F2E (Nama Perusahaan), F2E1 (Nama Atasan), F2E2 (Telepon Atasan), F2E3 (Email Atasan),
 *   F2F (Alamat Perusahaan), F2G (Posisi Jabatan), F2H (Skala Perusahaan),
 *   F8 (Status Pekerjaan), Kelompok F5 (F504, F502, F505, F505A, F506, F5a1, F5a2, F510, F5B, F5C, F5D),
 *   F11 (Jenis Perusahaan), F12 (Sumber Pembiayaan), F14 (Hubungan Bidang Studi), F15 (Tingkat Pendidikan Sesuai),
 *   F17 (Kompetensi F17a1..a7, F17b1..b7), dan F18 (Studi Lanjut F18a..d).
 * - Opsional (0): F2 (Header), F21 s.d. F27 (Metode Pembelajaran), F3, F4, F6, F7, F7A, F10, F16, F17 Header, F18 Header.
 */
class RefSubpertanyaan2021Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sections = KelompokPertanyaan::all()->keyBy('kode_kelompok');

        $questionsData = [
            // =========================================================
            // Kelompok 1: Identitas & Biodata Mahasiswa (Wajib Semua)
            // =========================================================
            [
                'section_kode' => '1',
                'kelompok' => 'F1',
                'kode_pertanyaan' => 'F1',
                'subpertanyaan' => 'Nomor Induk Mahasiswa (NIM)',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 1,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'F2A',
                'subpertanyaan' => 'Nama Lengkap Mahasiswa',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 2,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'F2B',
                'subpertanyaan' => 'Nomor Telepon / HP',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 3,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'F2C',
                'subpertanyaan' => 'Alamat Email',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 4,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'F2D',
                'subpertanyaan' => 'Alamat Tempat Tinggal Sekarang',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 5,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'BIO_TEMPAT_LAHIR',
                'subpertanyaan' => 'Tempat lahir',
                'type' => 'text',
                'keterangan' => 'Tempat lahir',
                'wajib' => 1,
                'order' => 6,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'BIO_TANGGAL_LAHIR',
                'subpertanyaan' => 'Tanggal lahir',
                'type' => 'text',
                'keterangan' => 'Tanggal lahir',
                'wajib' => 1,
                'order' => 7,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'BIO_JK',
                'subpertanyaan' => 'Jenis kelamin',
                'type' => 'radio',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 8,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'BIO_TGL_LULUS',
                'subpertanyaan' => 'Tanggal lulus',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 9,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'BIO_JUDUL_TA',
                'subpertanyaan' => 'Judul tugas akhir / skripsi',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 10,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'BIO_NIK',
                'subpertanyaan' => 'Nomor Induk Kependudukan (NIK)',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 11,
            ],
            [
                'section_kode' => '1',
                'kelompok' => 'BIO',
                'kode_pertanyaan' => 'BIO_NPWP',
                'subpertanyaan' => 'Nomor Pokok Wajib Pajak (NPWP)',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 12,
            ],

            // =========================================================
            // Kelompok 2: Penekanan Metode Pembelajaran (Opsional: F21 s.d. F27)
            // =========================================================
            [
                'section_kode' => '2',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F2',
                'subpertanyaan' => 'Menurut anda seberapa besar penekanan pada metode pembelajaran di bawah ini dilaksanakan di program studi anda?',
                'type' => 'header',
                'keterangan' => 'Penekanan metode pembelajaran',
                'wajib' => 0,
                'order' => 13,
            ],
            [
                'section_kode' => '2',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F21',
                'subpertanyaan' => 'Perkuliahan',
                'type' => 'radio',
                'keterangan' => 'Metode pembelajaran',
                'wajib' => 0,
                'order' => 14,
            ],
            [
                'section_kode' => '2',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F22',
                'subpertanyaan' => 'Demonstrasi',
                'type' => 'radio',
                'keterangan' => 'Metode pembelajaran',
                'wajib' => 0,
                'order' => 15,
            ],
            [
                'section_kode' => '2',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F23',
                'subpertanyaan' => 'Partisipasi dalam proyek riset',
                'type' => 'radio',
                'keterangan' => 'Metode pembelajaran',
                'wajib' => 0,
                'order' => 16,
            ],
            [
                'section_kode' => '2',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F24',
                'subpertanyaan' => 'Magang',
                'type' => 'radio',
                'keterangan' => 'Metode pembelajaran',
                'wajib' => 0,
                'order' => 17,
            ],
            [
                'section_kode' => '2',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F25',
                'subpertanyaan' => 'Praktikum',
                'type' => 'radio',
                'keterangan' => 'Metode pembelajaran',
                'wajib' => 0,
                'order' => 18,
            ],
            [
                'section_kode' => '2',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F26',
                'subpertanyaan' => 'Kerja Lapangan',
                'type' => 'radio',
                'keterangan' => 'Metode pembelajaran',
                'wajib' => 0,
                'order' => 19,
            ],
            [
                'section_kode' => '2',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F27',
                'subpertanyaan' => 'Diskusi',
                'type' => 'radio',
                'keterangan' => 'Metode pembelajaran',
                'wajib' => 0,
                'order' => 20,
            ],

            // =========================================================
            // Kelompok 3: Waktu Mulai & Cara Mencari Pekerjaan (Opsional)
            // =========================================================
            [
                'section_kode' => '3',
                'kelompok' => 'F3',
                'kode_pertanyaan' => 'F3',
                'subpertanyaan' => 'Kapan anda mulai mencari pekerjaan? Mohon pekerjaan sambilan tidak dimasukkan',
                'type' => 'radio_input',
                'keterangan' => 'F302 sebelum lulus, F303 sesudah lulus',
                'wajib' => 0,
                'order' => 21,
            ],
            [
                'section_kode' => '3',
                'kelompok' => 'F4',
                'kode_pertanyaan' => 'F4',
                'subpertanyaan' => 'Bagaimana anda mencari pekerjaan tersebut?',
                'type' => 'multiple_choice',
                'keterangan' => 'Jawaban bisa lebih dari satu',
                'wajib' => 0,
                'order' => 22,
            ],

            // =========================================================
            // Kelompok 4: Mendapatkan Pekerjaan & Data Pekerjaan (Wajib)
            // =========================================================
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F504',
                'subpertanyaan' => 'Apakah Anda telah mendapatkan pekerjaan ≤ 6 bulan, termasuk bekerja sebelum lulus?',
                'type' => 'radio',
                'keterangan' => 'Jika Ya jump to F502, jika Tidak jump to F506',
                'wajib' => 1,
                'order' => 23,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F502',
                'subpertanyaan' => 'Dalam berapa bulan anda mendapatkan pekerjaan ?',
                'type' => 'number',
                'keterangan' => 'Jumlah bulan setelah lulus',
                'wajib' => 1,
                'order' => 24,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F505',
                'subpertanyaan' => 'Berapa rata-rata pendapatan anda per bulan ? (take home pay)?',
                'type' => 'multiple_number',
                'keterangan' => 'Nominal Rupiah per bulan (Pekerjaan Utama, Lembur/Tips, Lainnya)',
                'wajib' => 1,
                'order' => 25,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F505A',
                'subpertanyaan' => 'Apakah Gaji anda sesuai UMR ?',
                'type' => 'radio',
                'keterangan' => 'Kesesuaian gaji dengan UMR',
                'wajib' => 1,
                'order' => 26,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F506',
                'subpertanyaan' => 'Dalam berapa bulan anda mendapatkan pekerjaan?',
                'type' => 'number',
                'keterangan' => 'Jumlah bulan',
                'wajib' => 1,
                'order' => 27,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F5a1',
                'subpertanyaan' => 'Provinsi tempat Anda bekerja',
                'type' => 'text',
                'keterangan' => 'ID Provinsi tempat bekerja',
                'wajib' => 1,
                'order' => 28,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F5a2',
                'subpertanyaan' => 'Kabupaten/Kota tempat Anda bekerja',
                'type' => 'text',
                'keterangan' => 'ID Kabupaten/Kota tempat bekerja',
                'wajib' => 1,
                'order' => 29,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F510',
                'subpertanyaan' => 'Di mana lokasi tempat Anda bekerja?',
                'type' => 'text',
                'keterangan' => 'Alamat lengkap tempat bekerja',
                'wajib' => 1,
                'order' => 30,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F5B',
                'subpertanyaan' => 'Apa nama perusahaan/kantor tempat Anda bekerja?',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 31,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F5C',
                'subpertanyaan' => 'Bila berwiraswasta, apa posisi/jabatan Anda saat ini?',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 32,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F5',
                'kode_pertanyaan' => 'F5D',
                'subpertanyaan' => 'Apa tingkat tempat kerja Anda?',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 33,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F2E',
                'subpertanyaan' => 'Nama perusahaan/instansi/institusi',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 34,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F2E1',
                'subpertanyaan' => 'Nama atasan di tempat bekerja',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 35,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F2E2',
                'subpertanyaan' => 'Nomor telepon atasan di tempat bekerja',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 36,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F2E3',
                'subpertanyaan' => 'Email atasan di tempat bekerja',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 37,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F2F',
                'subpertanyaan' => 'Alamat perusahaan/instansi/institusi',
                'type' => 'text',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 38,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F2G',
                'subpertanyaan' => 'Posisi jabatan Anda sekarang',
                'type' => 'radio',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 39,
            ],
            [
                'section_kode' => '4',
                'kelompok' => 'F2',
                'kode_pertanyaan' => 'F2H',
                'subpertanyaan' => 'Skala perusahaan/instansi/institusi',
                'type' => 'radio',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 40,
            ],

            // =========================================================
            // Kelompok 5: Riwayat Lamaran Pekerjaan (Opsional)
            // =========================================================
            [
                'section_kode' => '5',
                'kelompok' => 'F6',
                'kode_pertanyaan' => 'F6',
                'subpertanyaan' => 'Berapa perusahaan/instansi/institusi yang sudah Anda lamar sebelum memperoleh pekerjaan pertama?',
                'type' => 'number',
                'keterangan' => null,
                'wajib' => 0,
                'order' => 41,
            ],
            [
                'section_kode' => '5',
                'kelompok' => 'F7',
                'kode_pertanyaan' => 'F7',
                'subpertanyaan' => 'Berapa banyak perusahaan/instansi/institusi yang merespons lamaran Anda?',
                'type' => 'number',
                'keterangan' => null,
                'wajib' => 0,
                'order' => 42,
            ],
            [
                'section_kode' => '5',
                'kelompok' => 'F7',
                'kode_pertanyaan' => 'F7A',
                'subpertanyaan' => 'Berapa banyak perusahaan/instansi/institusi yang mengundang Anda untuk wawancara?',
                'type' => 'number',
                'keterangan' => null,
                'wajib' => 0,
                'order' => 43,
            ],

            // =========================================================
            // Kelompok 6: Status Pekerjaan Saat Ini (F8 Wajib, F10 Opsional)
            // =========================================================
            [
                'section_kode' => '6',
                'kelompok' => 'F8',
                'kode_pertanyaan' => 'F8',
                'subpertanyaan' => 'Jelaskan status Anda saat ini',
                'type' => 'radio',
                'keterangan' => 'Status pekerjaan saat ini',
                'wajib' => 1,
                'order' => 44,
            ],
            [
                'section_kode' => '6',
                'kelompok' => 'F10',
                'kode_pertanyaan' => 'F10',
                'subpertanyaan' => 'Apakah anda aktif mencari pekerjaan dalam 4 minggu terakhir?',
                'type' => 'radio',
                'keterangan' => 'Pilih satu jawaban',
                'wajib' => 0,
                'order' => 45,
            ],

            // =========================================================
            // Kelompok 7: Jenis Perusahaan & Pembiayaan Kuliah (Wajib Semua)
            // =========================================================
            [
                'section_kode' => '7',
                'kelompok' => 'F11',
                'kode_pertanyaan' => 'F11',
                'subpertanyaan' => 'Apa jenis perusahaan/instansi/institusi tempat Anda bekerja sekarang?',
                'type' => 'radio',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 46,
            ],
            [
                'section_kode' => '7',
                'kelompok' => 'F12',
                'kode_pertanyaan' => 'F12',
                'subpertanyaan' => 'Sebutkan sumber dana dalam pembiayaan kuliah',
                'type' => 'radio_input',
                'keterangan' => 'Pilihan sumber dana kuliah',
                'wajib' => 1,
                'order' => 47,
            ],

            // =========================================================
            // Kelompok 8: Keselarasan & Relevansi Pekerjaan (F14 & F15 Wajib, F16 Opsional)
            // =========================================================
            [
                'section_kode' => '8',
                'kelompok' => 'F14',
                'kode_pertanyaan' => 'F14',
                'subpertanyaan' => 'Seberapa erat hubungan antara bidang studi dengan pekerjaan Anda?',
                'type' => 'radio',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 48,
            ],
            [
                'section_kode' => '8',
                'kelompok' => 'F15',
                'kode_pertanyaan' => 'F15',
                'subpertanyaan' => 'Tingkat pendidikan apa yang paling tepat/sesuai untuk pekerjaan Anda saat ini?',
                'type' => 'radio',
                'keterangan' => null,
                'wajib' => 1,
                'order' => 49,
            ],
            [
                'section_kode' => '8',
                'kelompok' => 'F16',
                'kode_pertanyaan' => 'F16',
                'subpertanyaan' => 'Jika menurut anda pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
                'type' => 'multiple_choice',
                'keterangan' => 'Jawaban bisa lebih dari satu',
                'wajib' => 0,
                'order' => 50,
            ],

            // =========================================================
            // Kelompok 9: Evaluasi Kompetensi Lulusan (F17a1..a7 & F17b1..b7 Wajib)
            // =========================================================
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17',
                'subpertanyaan' => 'Pada saat lulus, pada tingkat mana kompetensi di bawah ini anda kuasai? (A) Pada saat ini, pada tingkat mana kompetensi di bawah ini diperlukan dalam pekerjaan? (B)',
                'type' => 'header',
                'keterangan' => 'Evaluasi kompetensi lulusan A dan B',
                'wajib' => 0,
                'order' => 51,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17a1',
                'subpertanyaan' => 'Etika',
                'type' => 'radio',
                'keterangan' => 'Pada saat lulus, kompetensi yang dikuasai (A)',
                'wajib' => 1,
                'order' => 52,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17b1',
                'subpertanyaan' => 'Etika',
                'type' => 'radio',
                'keterangan' => 'Pada saat ini, tingkat kompetensi yang diperlukan (B)',
                'wajib' => 1,
                'order' => 53,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17a2',
                'subpertanyaan' => 'Keahlian Berdasarkan Bidang Ilmu',
                'type' => 'radio',
                'keterangan' => 'Pada saat lulus, kompetensi yang dikuasai (A)',
                'wajib' => 1,
                'order' => 54,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17b2',
                'subpertanyaan' => 'Keahlian Berdasarkan Bidang Ilmu',
                'type' => 'radio',
                'keterangan' => 'Pada saat ini, tingkat kompetensi yang diperlukan (B)',
                'wajib' => 1,
                'order' => 55,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17a3',
                'subpertanyaan' => 'Bahasa Inggris',
                'type' => 'radio',
                'keterangan' => 'Pada saat lulus, kompetensi yang dikuasai (A)',
                'wajib' => 1,
                'order' => 56,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17b3',
                'subpertanyaan' => 'Bahasa Inggris',
                'type' => 'radio',
                'keterangan' => 'Pada saat ini, tingkat kompetensi yang diperlukan (B)',
                'wajib' => 1,
                'order' => 57,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17a4',
                'subpertanyaan' => 'Penggunaan Teknologi Informasi',
                'type' => 'radio',
                'keterangan' => 'Pada saat lulus, kompetensi yang dikuasai (A)',
                'wajib' => 1,
                'order' => 58,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17b4',
                'subpertanyaan' => 'Penggunaan Teknologi Informasi',
                'type' => 'radio',
                'keterangan' => 'Pada saat ini, tingkat kompetensi yang diperlukan (B)',
                'wajib' => 1,
                'order' => 59,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17a5',
                'subpertanyaan' => 'Komunikasi',
                'type' => 'radio',
                'keterangan' => 'Pada saat lulus, kompetensi yang dikuasai (A)',
                'wajib' => 1,
                'order' => 60,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17b5',
                'subpertanyaan' => 'Komunikasi',
                'type' => 'radio',
                'keterangan' => 'Pada saat ini, tingkat kompetensi yang diperlukan (B)',
                'wajib' => 1,
                'order' => 61,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17a6',
                'subpertanyaan' => 'Kerja sama tim',
                'type' => 'radio',
                'keterangan' => 'Pada saat lulus, kompetensi yang dikuasai (A)',
                'wajib' => 1,
                'order' => 62,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17b6',
                'subpertanyaan' => 'Kerja sama tim',
                'type' => 'radio',
                'keterangan' => 'Pada saat ini, tingkat kompetensi yang diperlukan (B)',
                'wajib' => 1,
                'order' => 63,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17a7',
                'subpertanyaan' => 'Pengembangan Diri',
                'type' => 'radio',
                'keterangan' => 'Pada saat lulus, kompetensi yang dikuasai (A)',
                'wajib' => 1,
                'order' => 64,
            ],
            [
                'section_kode' => '9',
                'kelompok' => 'F17',
                'kode_pertanyaan' => 'F17b7',
                'subpertanyaan' => 'Pengembangan Diri',
                'type' => 'radio',
                'keterangan' => 'Pada saat ini, tingkat kompetensi yang diperlukan (B)',
                'wajib' => 1,
                'order' => 65,
            ],

            // =========================================================
            // Kelompok 10: Studi Lanjut (F18a..d Wajib)
            // =========================================================
            [
                'section_kode' => '10',
                'kelompok' => 'F18',
                'kode_pertanyaan' => 'F18',
                'subpertanyaan' => 'Pertanyaan studi lanjut',
                'type' => 'header',
                'keterangan' => 'Bagi yang melanjutkan pendidikan',
                'wajib' => 0,
                'order' => 66,
            ],
            [
                'section_kode' => '10',
                'kelompok' => 'F18',
                'kode_pertanyaan' => 'F18a',
                'subpertanyaan' => 'Sumber biaya',
                'type' => 'text',
                'keterangan' => 'Sumber biaya studi lanjut',
                'wajib' => 1,
                'order' => 67,
            ],
            [
                'section_kode' => '10',
                'kelompok' => 'F18',
                'kode_pertanyaan' => 'F18b',
                'subpertanyaan' => 'Perguruan Tinggi',
                'type' => 'text',
                'keterangan' => 'Perguruan tinggi studi lanjut',
                'wajib' => 1,
                'order' => 68,
            ],
            [
                'section_kode' => '10',
                'kelompok' => 'F18',
                'kode_pertanyaan' => 'F18c',
                'subpertanyaan' => 'Program Studi',
                'type' => 'text',
                'keterangan' => 'Program studi studi lanjut',
                'wajib' => 1,
                'order' => 69,
            ],
            [
                'section_kode' => '10',
                'kelompok' => 'F18',
                'kode_pertanyaan' => 'F18d',
                'subpertanyaan' => 'Tanggal Masuk',
                'type' => 'text',
                'keterangan' => 'Tanggal masuk studi lanjut',
                'wajib' => 1,
                'order' => 70,
            ],
        ];

        foreach ($questionsData as $item) {
            $section = $sections[$item['section_kode']] ?? null;
            RefSubpertanyaan2021::updateOrCreate(
                ['kode_pertanyaan' => $item['kode_pertanyaan']],
                [
                    'kelompok' => $item['kelompok'],
                    'kelompok_pertanyaan_id' => $section?->id,
                    'subpertanyaan' => $item['subpertanyaan'],
                    'type' => $item['type'],
                    'keterangan' => $item['keterangan'],
                    'wajib' => $item['wajib'],
                    'order' => $item['order'],
                ]
            );
        }
    }
}
